### ISSUE TITLE
Line chart function not available after installing the package

### ISSUE THREAD

**Issue by cmg777** [thomas-neitmann/ggcharts#101]
![free_r_tips - master - RStudio 2021-12-21 09-01-29](https://user-images.githubusercontent.com/26156651/146848515-eab896d4-39ed-43f1-a7db-191d9daf7a4a.jpg)

**Comment by thomas-neitmann** [comment]
Please install the latest version from GitHub by running

```
if (!"remotes" %in% installed.packages()) {
  install.packages("remotes")
}
remotes::install_github("thomas-neitmann/ggcharts", upgrade = "never")
```

Then `line_chart()` should be available to you.
