### ISSUE TITLE
ggcharts PKG is great = quick question ref Interval / Range of values

### ISSUE THREAD

**Issue by sfd99** [thomas-neitmann/ggcharts#103]
**_Hi Thomas - Grüezi !._**

Really like the ggcharts PKG 
- easy and clear.

**quick Q:**
how do I specify 
in any ggcharts FX, 
(ie: lollipops),
- a greater-than / less-than condition
or 
- an Interval / Range of values ?

zb:
 plot all revenue Greater than 40...
 ```    lollipop_chart(revenue2016, company, revenue, threshold > 40)  ```
 or 
 plot in range btw 40 and 50...
```     lollipop_chart(revenue2016, company, revenue, threshold > 40 &&  threshold < 50 )   ```

Thanks / Danke!
**SFd99
SanFrancisco
Rstudio/Linux.**

**Comment by thomas-neitmann** [comment]
Such filtering behavior is not implemented and you would have to do it as a pre-processing step before passing your data into the plotting function.
