### ISSUE TITLE
Dynamic color for charts using fill

### ISSUE THREAD

**Issue by mayrop** [thomas-neitmann/ggcharts#13]
Do you have examples with the usage for `fill`?

I have the following code:
```R
items %>%
  dplyr::group_by(state) %>%
  dplyr::summarise(n = sum(n)) %>%
  dplyr::mutate(col = ifelse(n > 50, "#1F77B4", "#2CA02C")) %>%
  ggcharts::bar_chart(
    state, 
    n, 
    limit = 15,
    fill = col
  )
```

That produces the following plot:
<img width="350" src="https://user-images.githubusercontent.com/495985/74092844-672cf600-4a8f-11ea-9f5d-69ad63eb2d07.png">

If I add `+ scale_fill_identity()` it then produces:
<img width="350" src="https://user-images.githubusercontent.com/495985/74092834-482e6400-4a8f-11ea-85c1-d0a03ce16055.png">

So I wonder what's the correct usage when specifying the `fill` attribute for `ggplot`.

**Comment by thomas-neitmann** [comment]
Usually the `fill` aesthetic is used to color the bars based upon the value of another variable in your dataset. The colors used are taken from a color palette. In `ggcharts` I am using the color palette from Python's `matplotlib`.

```r
library(ggcharts)
library(dplyr)
library(gapminder)
data(gapminder)

gapminder %>%
  filter(year == 2007) %>%
  bar_chart(country, pop, fill = continent, limit = 10)
```
![image](https://user-images.githubusercontent.com/11788080/74106586-82b7ff80-4b68-11ea-90af-6cfbe4e047f3.png)

When you use `scale_fill_identity()` the values of the variable you specified as `fill` are interpreted as actuals colors. I could try to implement something that automatically calls `scale_fill_identity()` if the `fill` variable is called `color`, `colors` or `cols`. Would that be helpful?

**Comment by mayrop** [comment]
Yes, that'd be great!

**Comment by thomas-neitmann** [comment]
@mayrop I am wondering how useful this would actually be. When using `scale_fill_identity()` no legend is created. And without a legend the colors do not have a meaning...

**Comment by mayrop** [comment]
Well, I just thought it was a nice feature to have. For example, when working with medals for the Olympics, having colors in the Y axis (Gold/Silver/Bronze). I think that having the bars in their respective color looks nice. Also, when working with something for the US elections (Democrat/Republican/Other) is nice to paint them in Blue/Red/Gray. Right now, `ggcharts` gives you the opportunity to change 1 color and 1 highlight, but no way to change the whole palette (or maybe I haven't found the way to do it). It is not really needed as I mentioned above since you can add `+ scale_fill_identity()` at the end and make it happen ;)

**Comment by thomas-neitmann** [comment]
Changing the color palette is easy. Here is an example that uses a palette from the `RColorBrewer` package:
```r
library(ggcharts)
library(dplyr)
library(gapminder)
data(gapminder)

gapminder %>%
  filter(year == 2007) %>%
  bar_chart(country, pop, fill = continent, limit = 10) +
  scale_fill_brewer(palette = "Set1")
```
![image](https://user-images.githubusercontent.com/11788080/74595165-a7b3e300-503e-11ea-8964-22ddf3d7e0e4.png)

If you want to get really custom you can pass a named vector of colors to `scale_fill_manual()`, e.g.
```r
colors <- c("Africa" = "orange", "Asia" = "darkgreen", "Americas" = "darkred")
gapminder %>%
  filter(year == 2007) %>%
  bar_chart(country, pop, fill = continent, limit = 10) +
  scale_fill_manual(values = colors)
```
![image](https://user-images.githubusercontent.com/11788080/74595211-fd888b00-503e-11ea-9235-7c7e60e4c2d9.png)

In addition you can highlight multiple bars with different colors:
```r
gapminder %>%
  filter(year == 2007) %>%
  bar_chart(country, pop, limit = 10, highlight = c("China", "Nigeria"), bar_color = c("steelblue", "orange"))
```
![image](https://user-images.githubusercontent.com/11788080/74595238-67a13000-503f-11ea-95c6-a6024dce0752.png)

**Comment by mayrop** [comment]
Sounds good! Thank you! Great work btw!
