### ISSUE TITLE
Modify bar_chart {ggcharts} Example

### ISSUE THREAD

**Issue by gwd999** [thomas-neitmann/ggcharts#5]
Modify/Change `bar_chart`example from:  
`biomedicalrevenue %>%`  
  `filter(year == 2018) %>%`  
  `bar_chart(company, year, limit = 10)`   
to a potentially more pleasing: 
`...`   
`bar_chart(company, revenue, limit = 10)`

**Comment by thomas-neitmann** [comment]
What exactly is bothering you in this example, @gwd999? Is it the use of the `dplyr` package? I could instead rewrite it using base R to something like this:
```r
revenue2018 <- biomedicalrevenue[biomedicalrevenue$year == 2018, ]
bar_chart(revenue2018, company, revenue, limit = 10)
```

Notice that without using the pipe `%>%` you have to specify the `data.frame` as the first argument to `bar_chart()`. That's why `bar_chart(company, revenue, limit = 10)` wouldn't work.

**Comment by gwd999** [comment]
nothing bothering - it is just if you use 'year' you will just get e bunch of equally wide bars on top of each other. so not really a very "interesting" plot to show off bar_charts() use/potential   
If you change it ot revenue you will have e meaningful x axis and varying sizes of bars. 
That just looks more "useful" and practical as an example ... than 10 identical bars. 
So you can call it cosmetics or "Jammern auf hohem Niveau" 
PS: really convenient pkg ...

**Comment by thomas-neitmann** [comment]
It's only now that I realize the issue. What a miss on my side. The intention of this example was certainly to have the bars represent the revenue and not the year (just like in the README). Thank you very much for spotting this!
Bitte jammere auch in Zukunft auf hohem Niveau 😉

**Comment by gwd999** [comment]
> 
> 
> It's only now that I realize the issue. What a miss on my side. The intention of this example was certainly to have the bars represent the revenue and not the year (just like in the README). Thank you very much for spotting this!
> Bitte jammere auch in Zukunft auf hohem Niveau 😉

I had a a pull request in the planning -> but was not able to push to some branch - will close this issue and will try my best on constructive input.

**Comment by thomas-neitmann** [comment]
I fixed the example as well as the same error in the `lollipop_chart()` documentation. In addition I added lots of other examples to all `{ggcharts}` functions.
