### ISSUE TITLE
Error in (function (el, elname)  : 

### ISSUE THREAD

**Issue by LenmonChen** [thomas-neitmann/ggcharts#75]
When I try to use ggcharts, encounter Error

here is the code and error message：
base_plot <- ggplot(mtcars, aes(hp, mpg)) + geom_point(color = "gray")
 p1 <- base_plot + theme_ggcharts()

Error in (function (el, elname)  : 
  "plot.title.position" is not a valid theme element name.

**Comment by thomas-neitmann** [comment]
Thank you very much for reporting this @LenmonChen.

`"plot.title.position"` is a new theme element introduced in version 3.3.0 of `{ggplot2}`. For now you will have to upgrade your `{ggplot2}` version.

I will add a fix to only use `"plot.title.position"` if the `{ggplot2}` version is >= 3.3.0.

**Comment by thomas-neitmann** [comment]
I just fixed this issue and submitted a new version of the package to CRAN. In the meantime you can install the development version as described in the README.

**Comment by thomas-neitmann** [comment]
Version 0.2.1 of `{ggcharts}` with a fix for this bug is now available from CRAN.
