### ISSUE TITLE
theme_coffee() couldn't work

### ISSUE THREAD

**Issue by henrywangnl** [thomas-neitmann/ggcharts#95]
It seems that `theme_coffee()` doesn't work.
`Error in theme_coffee() : could not find function "theme_coffee"`

**Comment by thomas-neitmann** [comment]
Thanks for reporting this. You are most likely using the CRAN version. `theme_coffee()` is, however, only available in the development version that you can install from GitHub as described in the README.

**Comment by henrywangnl** [comment]
oops...
Thanks Thomas!
